name = "nft-appraisals-weights-calc"
version = "1.0.0"

[deployment]
nodes = 1

[build]
dir = "build"
entry = "nft-appraisals-weights-calc_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "nft-appraisals-weights-calc.wasm"
command = "npm run build:release"
