version: "3.8"

services:

  worker:
    command: >
      - upshot-node
      - --role=worker
      - --peer-db=/data/peerdb
      - --function-db=/data/function-db
      - --runtime-path=/app/runtime
      - --runtime-cli=bls-runtime
      - --workspace=/data/workspace
      - --private-key=/data/keys/priv.bin
      - --log-level=debug
      - --boot-nodes=/ip4/172.21.0.100/tcp/9010/p2p/head-id
      - --allora-chain-topic-id=1
      - --topic=1
    build: .
    volumes:
      - ./worker-data:/data
    working_dir: /data
    environment:
      - HOME=/app
    env_file:
      - .env
    depends_on:
      - head
    networks:
      b7s-local:
        aliases:
          - worker
        ipv4_address: 172.21.0.5

  head:
    command: >
      - upshot-node
      - --role=head
      - --peer-db=/data/peerdb
      - --function-db=/data/function-db
      - --runtime-path=/app/runtime
      - --runtime-cli=bls-runtime
      - --workspace=/data/workspace
      - --private-key=/data/keys/priv.bin
      - --log-level=debug
      - --port=9010
      - --rest-api=:6000
    image: alloranetwork/allora-inference-base-head:latest
    ports:
      - "6000:6000"
    volumes:
      - ./head-data:/data
    working_dir: /data
    environment:
      - HOME=/data
    networks:
      b7s-local:
        aliases:
          - head
        ipv4_address: 172.21.0.100

networks:
  b7s-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
